"""
Django settings for marmo project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECURE_CONTENT_TYPE_NOSNIFF = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7co!n2cx$=gymp740t3p)$3e@17^fm!(p7pdl+(a=9$!2!!hr#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.48","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'mptt',
    'background_task'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.verifymiddleware.VerifyLoginMiddleware',

]

ROOT_URLCONF = 'marmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'marmo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'marmo',
        'USER': 'root',
        'PASSWORD': 'derui@321',
        'PORT': '3306',
        'HOST': '192.168.0.48',
    },
}
CACHES ={
    "default":{
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:deruiA321@192.168.0.48:6379/15",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,"/static/")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_FINDERS = (
  'django.contrib.staticfiles.finders.FileSystemFinder',
  'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # media即为图片上传的根路径
MEDIA_URL = '/media/'

# 日志模块
LOG_PATH = os.path.join(BASE_DIR, 'logs')
# 如果地址不存在，则自动创建log文件夹
if not os.path.join(LOG_PATH):
    os.mkdir(LOG_PATH)

X_FRAME_OPTIONS="SAMEORIGIN"
PER_PAGE=100
LOGIN_URL="/login/"
mimetypes.add_type('text/css', '.css')
mimetypes.add_type('application/javascript', '.js')
CELERY_BROKER_URL = 'redis://:deruiA321@192.168.0.48:6379/13' # Broker配置，使用Redis作为消息中间件

CELERY_RESULT_BACKEND = 'redis://:deruiA321@192.168.0.48:6379/14' # BACKEND配置，这里使用redis
CELERY_RESULT_SERIALIZER = 'json' # 结果序列化方案

#模块名称:
MAINDOMAIN_MODULE="main_domain"
SUBDOMAIN_MODULE="subdomain"
CDN_MODULE="cdn"
WHOIS_INFO_MODULE="whois_info"
SIDE_STATIONS_MODULE="side_stations"
CRANGE_MODULE="crange"
IP_LOCATION_MODULE="ip_location"
#端口探测
PORT_SCAN_MODULE="portscan"
#端口banner探测
PORT_BANNER_MODULE="portbanner"
#web深度识别
WEB_ASSET_RECONGNIZE_MODULE="web_recongnize"
SCREENSHOT_MODULE="screenshot"
SSLINFO_MODULE="sslinfo"
DIRBUSTER_MODULE="dirbuster"
REAL_IP_RECONGNIZE_MODULE="real_ip"
#oneforall位置
ONEFORALLPATH="/data/OneForAll"
#chrome浏览器内核的地址
EXECUTE_PATH="/data/chromedriver"
#生成的截图的访问地址
IMAGE_URL="http://192.168.0.48/screenshot"
#生成的截图的存放路径
IMAGE_PATH="/home/marmo/screenshot/"
#任务队列
DOMAIN_TASK_LIST="marmo_domain_list"
IP_TASK_LIST="marmo_ip_list"
SERVICE_TASK_LIST="marmo_service_list"
TASK_RESULT="marmo_hash"
TEMP_FILE_PATH="/home/marmo"
CENSYS_API_ID="b3e6c17b-6fe6-49f6-94f4-371459b1ce0b"
CENSYS_API_SECRET="ZOdpIiqN93u9kLJH9WI2FhDgJvuGWTZu"
DIRBUSTER_DISTIONARY="/home/marmo/dirbuster/directory/dirb.txt"
DIRBUSTER_DEEP=1
DIRBUSTER_OUTPUT="/home/marmo/dirbuster/"
DIRBUSTER_COMMAND="/usr/local/bin/python3 /data/dirsearch/dirsearch.py -w %s -o %s -u %s"
#DIRBUSTER_COMMAND ='feroxbuster --auto-tune -kre -w %s -a "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" %s -d %d --output %s --json -u %s'
FOFA_EMAIL="sec@smartservice.com.cn"
FOFA_KEY="bfaec2da79d0955518c6beb581e09f47"
SHODAN_API_KEY="xm9ocLQkNCNRVOGV6pst2Je39jFVTT5n"
MASSCAN_FILE_PATH="/home/marmo/masscan"
RUSTSCAN_ALL_PORT_COMMAND="/usr/bin/rustscan -a %s --ulimit 5000 -g"
RUSTSCAN_PART_PORT_COMMAND="/usr/bin/rustscan -a %s --ulimit 5000 -g -p21,22,23,25,53,80,81,110,111,123,135,137,139,161,389,443,445,465,500,515,520,523,548,623,636,873,902,1080,1099,1433,1521,1604,1645,1701,1883,1900,2049,2181,2375,2379,2425,3128,3306,3389,4730,5060,5222,5351,5353,5432,5555,5601,5672,5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,27017,37777,50000,50070,61616"
MASSCAN_COMMAND="/usr/bin/masscan -p1-65535 --max-rate=500 %s -oJ %s"
PORT_TOP=50
PORTBANNERFILEPATH="/home/marmo/banner"
WAPPALYZER_APIKEY="pQ5FNt1YkOaQgvlGb2UJj33coiIVw3Bb9EuDRbp3"

'''
    命令
'''
ONEFORALL_COMMAND ="/usr/local/bin/python3 %s --fmt json --path %s --target %s run --brute=False"
GOBUSTER_FILEPATH="/home/marmo/gobuster"
GOBUSTER_COMMAND ="/usr/local/gopath/bin/gobuster dns  -t 50 -d %s -w /data/dns_final.txt -o %s"
PORTBANNER_COMMAND="nmap -Pn -sV -sC -p%s %s -oX %s"
SSLINFO_COMMAND ="sslscan  --show-certificate %s:%s"
SSLFINGERPRINT_COMMAND="openssl x509 -fingerprint -in %s"
CMSEEK_FILE_PATH="/data/CMSeeK/Result/%s/cms.json"
'''
    新建端口记录开始的状态
'''
SERVICE_CELERY_STATUS="9P"
IP_CELERY_STATUS="7P"
SUBDOMAIN_CELERY_STATUS="3P"